# This file has a bunch of record id, strength, and radius value for updrafts.
# All yaml files in this directory will be merged together, so you can
# add new files in a patch mod and they will be included automatically.
# The record ids should all be lowercased in these files.

terrain_ashmire_02:
  radius: 250
  strength: 0.5
